### ISSUE TITLE
The nav bar items within expression page are not intuitive.

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/lis_expression#3]
Steven pointed out that he was not sure what these are for.  
TO DO: 
Change the text to make them more clear OR add tooltips on hover ?

**Comment by sdash-github** [comment]
Added title attribute with tool tips. Need feedback if this makes it look ugly!!!

**Comment by StevenCannon-USDA** [comment]
It looks good to me, Sudhansu. Closing, unless there are objections.
